server:
  port: 9000

spring:
  main:
    web-application-type: reactive
  application:
      name: api-gateway
  cloud:
    gateway:
      routes:
        - id : auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/**
          filters:
            AuthenticationFilter
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog-service/**
          filters:
            AuthenticationFilter

        - id: eureka-service
          uri: lb://eureka-service
          predicates:
            - Path=/eureka-service/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

keycloak:
  resource: REFOCL2N1045IN1045
  realm: Refo
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8080}
  ssl-required: none
  credentials:
    secret: TYpmKtoH10iFC8dCGBsrVrj8D3JWMZ5U
  use-resource-role-mappings: true
  bearer-only: true
